<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Scada.Drivers</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scada.Core\Scada.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentModbus" />
  </ItemGroup>
</Project>
